use_default_settings: true

general:
  debug: false
  instance_name: "ARGUS Search"

search:
  safe_search: 1
  formats:
    - html
    - json

server:
  limiter: false
  image_proxy: false
  secret_key: "overridden-by-SEARXNG_SECRET"

ui:
  static_use_hash: true

outgoing:
  request_timeout: 8.0
  max_request_timeout: 15.0
